### ISSUE TITLE
The client doesn't receive the reply

### ISSUE THREAD

**Issue by pax-k** [Niurmiguel/nestjs-service-bus#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have 1 producer and 1 consumer. The subscriber returns some data and the producer should receive the reply, but it doesn't. My topic is `books` and I also created `books.reply` in Azure Service Bus.

Producer:
```
    const pattern: AzureServiceBusSenderOptions = {
      name: 'books',
    };
    const data = {
      body: 'ping',
    };
    console.log('sending');
    this.sbClient.send(pattern, data).subscribe((response) => {
      console.log('received:', response); // i expect to receive pong, but i don't
    });
```
Consumer:
```
  @Subscription({
    topic: 'books',
    subscription: 'getMessages',
    receiveMode: 'receiveAndDelete',
  })
  getMessages(@Payload() message: ServiceBusMessage) {
    console.log(message.body); // correctly receives the ping message
    return 'pong'; // i return pong, expecting it will be sent back to the producer
  }
```

Can you please help?

Thank you

### Expected behavior

I expect to receive `pong`

### Packages versions

latest

### Node.js version

18.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by ihaalar** [comment]
How are you able to receive messaages  ? My code similar to yours doesn't get triggered. getMessages() is never triggered in my code.

 @Subscription({
    topic: 'my-topic',
    subscription: 'my-sub',
    receiveMode: 'receiveAndDelete',
  })
  getMessages(@Payload() message: ServiceBusMessage) {
    console.log(message.body); 
  }
